%YAML 1.2
---
processed_data_home: ../../cocoa/cocoa/processed

model_config: ./config/model/llama-32.yaml
max_seq_len: !!int &max_len 4096
n_epochs: !!int 2

wandb:
  project: cotorra
  run_name: &run_name cotorra-sco_re-final
output_dir: ./output

custom_loss: !!bool false

training_args:
  report_to: wandb
  run_name: *run_name
  per_device_train_batch_size: !!int 8
  per_device_eval_batch_size: !!int 8
  save_total_limit: !!int 1
  metric_for_best_model: eval_loss
  load_best_model_at_end: !!bool true
  greater_is_better: !!bool false
  eval_strategy: steps
  save_strategy: best
  prediction_loss_only: !!bool true
  ddp_find_unused_parameters: !!bool false
  neftune_noise_alpha: !!float 5.0
  #auto_find_batch_size: !!bool true
  learning_rate: !!float 2e-4
  gradient_accumulation_steps: !!int 1
  remove_unused_columns: !!bool false # otherwise `s_elapsed` is automatically dropped
  #max_steps: !!int 100 # uncomment for testing purposes only
  bf16: !!bool true

tuning_args:
  direction: minimize
  backend: optuna
  n_trials: !!int 5

extract:
  max_len: *max_len
  batch_size: !!int 64
  time_limit_s: !!int 86400 # 24 hours
